export const SET_LOADING = "SET_LOADING";

export const GET_ALL_ARTICLES = "GET_ALL_ARTICLES";
export const GET_ALL_ARTICLES_ERROR = "GET_ALL_ARTICLES_ERROR";

export const GET_ARTICLE_BY_ID = "GET_ARTICLE_BY_ID";
export const GET_ARTICLE_BY_ID_ERROR = "GET_ARTICLE_BY_ID_ERROR";

export const UPDATE_LIKES = "UPDATE_LIKES";
export const UPDATE_LIKES_ERROR = "UPDATE_LIKES_ERROR";

export const UPDATE_UNLIKES = "UPDATE_UNLIKES";
export const UPDATE_UNLIKES_ERROR = "UPDATE_UNLIKES_ERROR";

export const BLOCK_ARTICLE = "BLOCK_ARTICLE";
export const BLOCK_ARTICLE_ERROR = "BLOCK_ARTICLE_ERROR";

export const GET_USER_ARTICLES = "GET_USER_ARTICLES";
export const GET_USER_ARTICLES_ERROR = "GET_USER_ARTICLES_ERROR";

export const DELETE_USER_ARTICLE = "DELETE_USER_ARTICLE";
export const DELETE_USER_ARTICLE_ERROR = "DELETE_USER_ARTICLE_ERROR";

export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const CREATE_ARTICLE_ERROR = "CREATE_ARTICLE_ERROR";

export const EDIT_ARTICLE = "EDIT_ARTICLE";
export const EDIT_ARTICLE_ERROR = "EDIT_ARTICLE_ERROR";
