//User Register
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// User Authentication
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

// Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

//Edit User Settings
export const EDIT_USER_SETTINGS = "EDIT_USER_SETTINGS";
export const EDIT_USER_SETTINGS_ERROR = "EDIT_USER_SETTINGS_ERROR";

//Follow User
export const FOLLOW_USER = "FOLLOW_USER";

//Logout
export const LOGOUT = "LOGOUT";

//OTP
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const  RESEND_OTP_ERROR = "RESEND_OTP_ERROR";

//Forgot Password
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
